[window]
opacity = 0.35
padding.x = 5
padding.y = 5
[font]
size = 14.0
[font.normal]
family = "EnvyCoder Nerd Font"

[general]
import = [ "~/.config/alacritty/themes/glass.toml" ]
[cursor.style]
shape = "Beam"
blinking = "Always"


[bell]
duration = 0
